export const ProductStage = {
    NEW_PRODUCTION: 'NEW PRODUCTION',
    EXPORT_TO_AGENCY: 'EXPORT TO AGENCY',
    SOLD: 'SOLD',
    NEED_REPAIR: 'NEED REPAIR',
    REPAIRING: 'REPAIRING',
    REPAIRED: 'REPAIRED',
    RETURNED_TO_CUSTOMER: 'RETURNED TO CUSTOMER',
    NEED_RETURN_TO_FACTORY: 'NEED RETURN TO FACTORY',
    RETURNED_TO_FACTORY: 'RETURNED TO FACTORY',
    NEED_RECALL: 'NEED RECALL',
    WARRANTY_EXPIRED: 'WARRANTY EXPIRED',
    CANNOT_SOLD: 'CANNOT SOLD'
}